config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    resources :posts do
      resources :comment, only: [:new, :create]
      resources :like, only: [:create]
      resources :book_mark, only: [:create]

      # RESOURCE, SCOPE
      # /CONTROLLERS/:ID/METHOD
      member do
        delete 'delete', to: 'posts#destroy_post_waiting_admin_confirm'
        post 'confirm', to: 'posts#confirm_post'
        post 'cancel', to: 'posts#cancel_post'
      end

      # /CONTROLERS/METHOD
      collection do
        get :bookmarked
        get :liked
        get :confirming
        get :waiting_confirmations
        get :published , to: 'posts#published'
      end
    end

    namespace :standard do
      resources :home
    end

    devise_scope :user do
      scope module: :password, controller: 'account' do

      end
      get 'password/change', to: 'standard/account#change_password', as: :change_password
      put 'password/change', to: 'standard/account#change_password_put', as: :change_password_put
      get 'profile', to: 'standard/home#show', as: :profile
    end

    devise_for :user, path: 'auth',
      path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                    confirmation: 'comfirm', unlock: 'unblock', registration: 'register',
                    sign_up: 'sign-up'
                  },
      controllers:{registrations: 'user/registrations',
                    sessions: 'user/sessions',
                    passwords: 'user/passwords',
                    unlocks: 'user/unlocks',
                    confirmation: 'user/confirmations'
                  }
  end
  get '/:locale' => 'standard/home#index'
  root 'standard/home#index'
end

app/controllers/standard/account_controller.rb
module Standard
  class ChangeInfoController < BaseController
    def change_password
      @user = current_user
    end

    def change_password_put
        service.update(current_user,parameters.password_params)
        flash[:success] = I18n.t(".devise.passwords.updated")
        redirect_to new_user_session_path
      rescue Exception => e
        flash[:error] = "error: #{e.message}"
        redirect_to change_password_path
    end
    private
    def parameters
      @params ||= User::RegistrationParams.new params
    end
    def service
      service ||= User::RegistrationService.new
    end
  end
end

app/controllers/standard/home_controller.rb
module Standard
  class HomeController < DashboardController

    def index;end

    def show
      @user = current_user if user_signed_in?
      @statistic = Home::StatisticSupporter.new
    end

    private
    def parameters
      @params ||= Record::PostParams.new params
    end

    def home_service
      @home_service ||= Record::HomeService.new current_user
    end
  end
end

app/helpers/standard/change_info_helper.rb
module Standard::ChangeInfoHelper
end

app/helpers/standard/home_helper.rb
module Standard::HomeHelper
    
end

app/helpers/standard/post_helper.rb
module Standard::PostHelper
end

app/views/standard/account/change_password.html.slim
body.text-center

  h2
    | Change Password
  br
  p
    | Nếu thay đổi password bạn phải đăng nhập laị !!!!
  .form-signin

   = form_for @user, url: change_password_put_path, html: { method: :put}  do |f|
    br

    = f.label :password, class: 'sr-only'
    = f.password_field :password, id: "password",autocomplete: "new-password", class: 'form-control', placeholder: 'new password'

    = f.label :password_confirmation, class: 'sr-only'
    = f.password_field :password_confirmation, id: "confirm_password", autocomplete: "new-password", class: 'form-control', placeholder: 'confim new password'

    =f.submit "Change Password", class: 'btn btn-lg btn-primary btn-block'

  = link_to  " Home >>", root_path